version: '3.7'

services:
  http-proxy:
    image: tiagostutz/simple-gzip-proxy:0.2.1
    build: 
      context: .
      args:
        ENABLED_MODULES: headers-more-nginx-module
    ports:
      - "4480:80"
    environment:  
      - PROXY_URI=http://host.docker.internal:4466
      - CORS_ORIGIN=*
  
  whoami:
    image: containous/whoami
    ports:
      - "4400:80"
