version: '3.7'

services:
  http-proxy:
    image: tiagostutz/simple-gzip-proxy
    build: .
    ports:
      - "4480:80"
    environment:  
      - PROXY_URI=http://whoami:80
  
  whoami:
    image: containous/whoami
    ports:
      - "4400:80"
